#!/usr/bin/env python3
"""Query a call graph JSON generated by build_call_graph.py.

Examples:

    python query_call_graph.py pt016_call_graph.json ControlPro
    python query_call_graph.py pt016_call_graph.json main --max-depth 3 --json
    python query_call_graph.py pt016_call_graph.json --function-id PT016/main.c:7:main
    python query_call_graph.py pt016_call_graph.json --global _ushSelfThreeState
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Set, Tuple


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("call_graph_json", help="Path to call_graph.json")
    parser.add_argument(
        "function",
        nargs="?",
        help="Function name or qualified name to query",
    )
    parser.add_argument(
        "--function-id",
        help="Exact function id to query, e.g. PT016/main.c:7:main",
    )
    parser.add_argument(
        "--global",
        dest="global_name",
        help="Global variable name to query",
    )
    parser.add_argument(
        "--max-depth",
        type=int,
        default=None,
        help="Maximum recursive expansion depth. Default is unlimited.",
    )
    parser.add_argument(
        "--direction",
        choices=("forward", "backward", "both"),
        default="forward",
        help="Traversal direction: callees, callers, or both. Default is forward.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print full structured JSON instead of the default compact JSON",
    )
    parser.add_argument(
        "--include-source",
        action="store_true",
        help="Include original function source code on tree/function nodes when available",
    )
    parser.add_argument(
        "--output",
        "-o",
        help="Write output JSON to a file",
    )
    return parser.parse_args()


def load_call_graph(path: Path) -> Dict[str, object]:
    with path.open("r", encoding="utf-8") as fh:
        payload = json.load(fh)
    if "functions" not in payload or "function_index" not in payload:
        raise SystemExit(f"Invalid call graph file: {path}")
    return payload


def validate_query_mode(args: argparse.Namespace) -> None:
    has_function_selector = bool(args.function or args.function_id)
    has_global_selector = bool(args.global_name)
    if has_function_selector and has_global_selector:
        raise SystemExit("Choose either function query mode or --global mode, not both.")
    if not has_function_selector and not has_global_selector:
        raise SystemExit("Provide a function name / --function-id, or use --global.")


def resolve_function_ids(
    payload: Dict[str, object],
    function_name: Optional[str],
    function_id: Optional[str],
) -> List[str]:
    functions = payload["functions"]
    function_index = payload["function_index"]

    if function_id:
        if function_id not in functions:
            raise SystemExit(f"Function id not found: {function_id}")
        return [function_id]

    if not function_name:
        raise SystemExit("You must provide either a function name or --function-id.")

    candidates = function_index.get(function_name, [])
    if candidates:
        return sorted(candidates)

    matches = []
    for current_id, info in functions.items():
        if info["name"] == function_name or info["qualified_name"] == function_name:
            matches.append(current_id)
    if matches:
        return sorted(matches)

    raise SystemExit(f"Function not found: {function_name}")


def resolve_global_name(payload: Dict[str, object], global_name: str) -> str:
    global_index = payload.get("global_index", {})
    if global_name in global_index:
        return global_name

    matches = sorted(name for name in global_index if name.lower() == global_name.lower())
    if len(matches) == 1:
        return matches[0]
    if len(matches) > 1:
        raise SystemExit(
            "Multiple globals match case-insensitively: " + ", ".join(matches)
        )
    raise SystemExit(f"Global variable not found: {global_name}")


def dedupe_preserve_order(items: Iterable[str]) -> List[str]:
    seen: Set[str] = set()
    result: List[str] = []
    for item in items:
        if item in seen:
            continue
        seen.add(item)
        result.append(item)
    return result


def resolve_callee_ids(functions: Dict[str, Dict[str, object]], function: Dict[str, object]) -> List[str]:
    resolved: List[str] = []
    for call in function.get("calls", []):
        resolved.extend(call.get("resolved_targets", []))
    return dedupe_preserve_order(resolved)


def resolve_neighbor_ids(
    payload: Dict[str, object],
    functions: Dict[str, Dict[str, object]],
    function_id: str,
    direction: str,
) -> List[str]:
    call_graph = payload.get("call_graph", {})
    forward = call_graph.get("forward", {})
    reverse = call_graph.get("reverse", {})

    if direction == "forward":
        if function_id in forward:
            return list(forward[function_id])
        return list(functions[function_id].get("callee_ids", []))
    if direction == "backward":
        if function_id in reverse:
            return list(reverse[function_id])
        return list(functions[function_id].get("caller_ids", []))

    both = []
    both.extend(forward.get(function_id, functions[function_id].get("callee_ids", [])))
    both.extend(reverse.get(function_id, functions[function_id].get("caller_ids", [])))
    return dedupe_preserve_order(both)


def find_global_accessors(
    functions: Dict[str, Dict[str, object]],
    global_name: str,
) -> Dict[str, List[str]]:
    readers: List[str] = []
    writers: List[str] = []
    touchers: List[str] = []

    for function_id, info in functions.items():
        reads = set(info.get("global_reads", []))
        writes = set(info.get("global_writes", []))
        if global_name in reads or global_name in writes:
            touchers.append(function_id)
        if global_name in reads:
            readers.append(function_id)
        if global_name in writes:
            writers.append(function_id)

    return {
        "readers": sorted(readers),
        "writers": sorted(writers),
        "touchers": sorted(touchers),
    }


def walk_reachable(
    payload: Dict[str, object],
    functions: Dict[str, Dict[str, object]],
    root_id: str,
    max_depth: Optional[int],
    direction: str,
) -> Tuple[Set[str], Dict[str, List[str]], Dict[str, bool]]:
    reachable: Set[str] = set()
    adjacency: Dict[str, List[str]] = {}
    cycle_edges: Dict[str, bool] = {}

    def dfs(current_id: str, depth: int, stack: Tuple[str, ...]) -> None:
        reachable.add(current_id)
        if max_depth is not None and depth >= max_depth:
            adjacency[current_id] = []
            return

        neighbors = resolve_neighbor_ids(payload, functions, current_id, direction)
        adjacency[current_id] = neighbors

        for neighbor_id in neighbors:
            edge_key = f"{current_id}->{neighbor_id}"
            if neighbor_id in stack:
                cycle_edges[edge_key] = True
                reachable.add(neighbor_id)
                continue
            if neighbor_id not in reachable:
                dfs(neighbor_id, depth + 1, stack + (neighbor_id,))
            else:
                cycle_edges.setdefault(edge_key, False)

    dfs(root_id, 0, (root_id,))
    return reachable, adjacency, cycle_edges


def build_tree(
    payload: Dict[str, object],
    functions: Dict[str, Dict[str, object]],
    root_id: str,
    max_depth: Optional[int],
    direction: str,
    include_source: bool = False,
) -> Dict[str, object]:
    def add_source(node: Dict[str, object], function: Dict[str, object]) -> None:
        if include_source and function.get("source") is not None:
            node["source"] = function["source"]

    def expand(current_id: str, depth: int, stack: Tuple[str, ...]) -> Dict[str, object]:
        info = functions[current_id]
        node = {
            "id": current_id,
            "name": info["name"],
            "qualified_name": info["qualified_name"],
            "file": info["file"],
            "line": info["line"],
            "global_reads": info.get("global_reads", []),
            "global_writes": info.get("global_writes", []),
            "direction": direction,
            "children": [],
        }
        add_source(node, info)

        if max_depth is not None and depth >= max_depth:
            node["truncated"] = True
            return node

        for neighbor_id in resolve_neighbor_ids(payload, functions, current_id, direction):
            if neighbor_id in stack:
                recursive_node = {
                    "id": neighbor_id,
                    "name": functions[neighbor_id]["name"],
                    "qualified_name": functions[neighbor_id]["qualified_name"],
                    "file": functions[neighbor_id]["file"],
                    "line": functions[neighbor_id]["line"],
                    "recursive": True,
                }
                add_source(recursive_node, functions[neighbor_id])
                node["children"].append(recursive_node)
                continue
            node["children"].append(expand(neighbor_id, depth + 1, stack + (neighbor_id,)))
        return node

    return expand(root_id, 0, (root_id,))


def summarize_reachable(
    functions: Dict[str, Dict[str, object]],
    globals_index: Dict[str, List[Dict[str, object]]],
    reachable: Set[str],
    include_source: bool = False,
) -> Dict[str, object]:
    ordered_ids = sorted(
        reachable,
        key=lambda function_id: (
            functions[function_id]["file"],
            functions[function_id]["line"],
            functions[function_id]["qualified_name"],
        ),
    )

    global_reads: Set[str] = set()
    global_writes: Set[str] = set()
    global_touchers: Dict[str, Set[str]] = defaultdict(set)

    for function_id in ordered_ids:
        info = functions[function_id]
        for name in info.get("global_reads", []):
            global_reads.add(name)
            global_touchers[name].add(function_id)
        for name in info.get("global_writes", []):
            global_writes.add(name)
            global_touchers[name].add(function_id)

    all_globals = sorted(global_reads | global_writes)
    reachable_functions = [
        {
            "id": function_id,
            "name": functions[function_id]["name"],
            "qualified_name": functions[function_id]["qualified_name"],
            "file": functions[function_id]["file"],
            "line": functions[function_id]["line"],
            "global_reads": functions[function_id].get("global_reads", []),
            "global_writes": functions[function_id].get("global_writes", []),
        }
        for function_id in ordered_ids
    ]
    if include_source:
        for function_info, function_id in zip(reachable_functions, ordered_ids):
            if functions[function_id].get("source") is not None:
                function_info["source"] = functions[function_id]["source"]

    return {
        "reachable_function_ids": ordered_ids,
        "reachable_functions": reachable_functions,
        "global_reads": sorted(global_reads),
        "global_writes": sorted(global_writes),
        "globals": {
            name: {
                "definitions": globals_index.get(name, []),
                "touched_by": sorted(global_touchers.get(name, [])),
                "modes": sorted(
                    mode
                    for mode, names in (
                        ("read", global_reads),
                        ("write", global_writes),
                    )
                    if name in names
                ),
            }
            for name in all_globals
        },
    }


def summarize_roots(
    payload: Dict[str, object],
    functions: Dict[str, Dict[str, object]],
    root_ids: Sequence[str],
    globals_index: Dict[str, List[Dict[str, object]]],
    max_depth: Optional[int],
    direction: str,
    include_source: bool = False,
) -> Dict[str, object]:
    combined_reachable: Set[str] = set()
    root_summaries: List[Dict[str, object]] = []

    for root_id in root_ids:
        reachable, adjacency, cycle_edges = walk_reachable(payload, functions, root_id, max_depth, direction)
        combined_reachable.update(reachable)
        root_summaries.append(
            {
                "root_function_id": root_id,
                "root_function_name": functions[root_id]["name"],
                "root_qualified_name": functions[root_id]["qualified_name"],
                "tree": build_tree(payload, functions, root_id, max_depth, direction, include_source),
                "reachable_function_ids": sorted(reachable),
                "adjacency": adjacency,
                "cycle_edges": sorted(edge for edge, is_cycle in cycle_edges.items() if is_cycle),
            }
        )

    return {
        "root_expansions": root_summaries,
        "combined": summarize_reachable(functions, globals_index, combined_reachable, include_source),
    }


def compact_function_summary(function: Dict[str, object], include_source: bool = False) -> Dict[str, object]:
    summary = {
        "id": function["id"],
        "file": function["file"],
        "line": function["line"],
        "qname": function["qualified_name"],
        "reads": function.get("global_reads", []),
        "writes": function.get("global_writes", []),
        "calls": dedupe_preserve_order(
            callee_id
            for call in function.get("calls", [])
            for callee_id in call.get("resolved_targets", [])
        ),
    }
    if include_source and function.get("source") is not None:
        summary["source"] = function["source"]
    return summary


def compact_tree(tree: Dict[str, object], include_source: bool = False) -> Dict[str, object]:
    node = {
        "id": tree["id"],
        "file": tree.get("file"),
        "line": tree.get("line"),
        "qname": tree.get("qualified_name"),
        "reads": tree.get("global_reads", []),
        "writes": tree.get("global_writes", []),
        "children": [
            compact_tree(child, include_source)
            for child in tree.get("children", [])
        ],
    }
    if tree.get("recursive"):
        node["recursive"] = True
    if tree.get("truncated"):
        node["truncated"] = True
    if include_source and tree.get("source") is not None:
        node["source"] = tree["source"]
    return node


def compact_tree_edges(tree: Dict[str, object]) -> List[Dict[str, object]]:
    edges: List[Dict[str, object]] = []

    def visit(node: Dict[str, object]) -> None:
        current_id = node["id"]
        for child in node.get("children", []):
            edges.append(
                {
                    "caller": current_id,
                    "callee": child["id"],
                    "recursive": bool(child.get("recursive", False)),
                }
            )
            if not child.get("recursive", False):
                visit(child)

    visit(tree)
    return edges


def build_compact_result(
    result: Dict[str, object],
    functions: Dict[str, Dict[str, object]],
    include_source: bool = False,
) -> Dict[str, object]:
    mode = result["query"]["mode"]
    if mode == "function":
        root_id = result["query"]["root_function_id"]
        summary = result["summary"]
        reachable_ids = summary["reachable_function_ids"]
        reachable_functions = [
            compact_function_summary(functions[function_id], include_source)
            for function_id in reachable_ids
        ]
        globals_compact = [
            {
                "name": name,
                "modes": summary["globals"][name]["modes"],
                "touched_by": summary["globals"][name]["touched_by"],
            }
            for name in sorted(summary["globals"])
        ]
        return {
            "schema": "function_compact_v2" if include_source else "function_compact_v1",
            "query": {
                "mode": "function",
                "root": root_id,
                "direction": result["query"]["direction"],
                "depth": result["query"]["max_depth"],
                "include_source": include_source,
            },
            "root": compact_function_summary(functions[root_id], include_source),
            "tree": compact_tree(result["tree"], include_source),
            "reachable_functions": reachable_functions,
            "edges": compact_tree_edges(result["tree"]),
            "globals": globals_compact,
        }

    global_name = result["query"]["global_name"]
    metadata = result["global"]["metadata"]
    combined = result["expansion"]["combined"]
    root_expansions = result["expansion"]["root_expansions"]
    reachable_ids = combined["reachable_function_ids"]
    reachable_functions = [
        compact_function_summary(functions[function_id], include_source)
        for function_id in reachable_ids
    ]
    globals_compact = [
        {
            "name": name,
            "modes": combined["globals"][name]["modes"],
            "touched_by": combined["globals"][name]["touched_by"],
        }
        for name in sorted(combined["globals"])
    ]
    accessor_roots = [
        {
            "root": item["root_function_id"],
            "tree": compact_tree(item["tree"], include_source),
            "edges": compact_tree_edges(item["tree"]),
        }
        for item in root_expansions
    ]
    direct_accessors = [
        {
            "id": function_id,
            "file": functions[function_id]["file"],
            "line": functions[function_id]["line"],
            "qname": functions[function_id]["qualified_name"],
            "access": (
                "readwrite"
                if global_name in functions[function_id].get("global_reads", [])
                and global_name in functions[function_id].get("global_writes", [])
                else "read"
                if global_name in functions[function_id].get("global_reads", [])
                else "write"
            ),
            **(
                {"source": functions[function_id]["source"]}
                if include_source and functions[function_id].get("source") is not None
                else {}
            ),
        }
        for function_id in result["global"]["toucher_function_ids"]
    ]
    return {
        "schema": "global_compact_v2" if include_source else "global_compact_v1",
        "query": {
            "mode": "global",
            "global": global_name,
            "direction": result["query"]["direction"],
            "depth": result["query"]["max_depth"],
            "include_source": include_source,
        },
        "target_global": {
            "name": global_name,
            "decl_files": metadata.get("declaration_files", []),
            "include_sources": metadata.get("directly_including_source_files", []),
        },
        "direct_accessors": direct_accessors,
        "reachable_functions": reachable_functions,
        "accessor_expansions": accessor_roots,
        "related_globals": globals_compact,
    }


def query_function_result(
    payload: Dict[str, object],
    function_id: str,
    max_depth: Optional[int] = 3,
    direction: str = "forward",
    include_source: bool = False,
) -> Dict[str, object]:
    functions = payload.get("functions") or {}
    if function_id not in functions:
        raise ValueError(f"Function id not found: {function_id}")

    normalized_direction = "backward" if direction == "reverse" else (direction or "forward")
    if normalized_direction not in {"forward", "backward", "both"}:
        normalized_direction = "forward"

    reachable, adjacency, cycle_edges = walk_reachable(
        payload,
        functions,
        function_id,
        max_depth,
        normalized_direction,
    )
    tree = build_tree(
        payload,
        functions,
        function_id,
        max_depth,
        normalized_direction,
        include_source,
    )
    summary = summarize_reachable(
        functions,
        payload.get("globals", {}) or {},
        reachable,
        include_source,
    )
    return {
        "query": {
            "mode": "function",
            "root_function_id": function_id,
            "root_function_name": functions[function_id]["name"],
            "root_qualified_name": functions[function_id]["qualified_name"],
            "max_depth": max_depth,
            "direction": normalized_direction,
            "include_source": include_source,
        },
        "tree": tree,
        "summary": summary,
        "graph": {
            "adjacency": adjacency,
            "cycle_edges": sorted(edge for edge, is_cycle in cycle_edges.items() if is_cycle),
        },
    }


def write_json_output(payload: Dict[str, object], output_path: Optional[str]) -> None:
    if output_path:
        path = Path(output_path).resolve()
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8") as fh:
            json.dump(payload, fh, ensure_ascii=False, indent=2)
            fh.write("\n")
        return
    json.dump(payload, sys.stdout, ensure_ascii=False, indent=2)
    sys.stdout.write("\n")

def print_disambiguation(functions: Dict[str, Dict[str, object]], candidates: Sequence[str]) -> None:
    print("Multiple matching functions found. Use --function-id with one of:")
    for function_id in candidates:
        function = functions[function_id]
        print(f"  {function_id} :: {function['file']}:{function['line']}")


def print_global_disambiguation(payload: Dict[str, object], global_name: str) -> None:
    matches = sorted(
        name for name in payload.get("global_index", {}) if global_name.lower() in name.lower()
    )
    if not matches:
        return
    print("Similar global names:")
    for name in matches[:20]:
        print(f"  {name}")

def main() -> int:
    args = parse_args()
    validate_query_mode(args)
    payload = load_call_graph(Path(args.call_graph_json).resolve())
    functions = payload["functions"]
    globals_index = payload.get("globals", {})
    global_index = payload.get("global_index", {})

    if args.global_name:
        try:
            global_name = resolve_global_name(payload, args.global_name)
        except SystemExit:
            print_global_disambiguation(payload, args.global_name)
            raise

        metadata = global_index.get(global_name, {})
        accessors = find_global_accessors(functions, global_name)
        root_summary = summarize_roots(
            payload,
            functions,
            accessors["touchers"],
            globals_index,
            args.max_depth,
            args.direction,
            args.include_source,
        )
        result = {
            "query": {
                "mode": "global",
                "global_name": global_name,
                "max_depth": args.max_depth,
                "direction": args.direction,
                "include_source": args.include_source,
            },
            "global": {
                "metadata": metadata,
                "reader_function_ids": accessors["readers"],
                "writer_function_ids": accessors["writers"],
                "toucher_function_ids": accessors["touchers"],
            },
            "expansion": root_summary,
        }
    else:
        candidates = resolve_function_ids(payload, args.function, args.function_id)
        if len(candidates) > 1 and not args.function_id:
            print_disambiguation(functions, candidates)
            return 2

        root_id = candidates[0]
        root_function = functions[root_id]
        reachable, adjacency, cycle_edges = walk_reachable(
            payload,
            functions,
            root_id,
            args.max_depth,
            args.direction,
        )
        tree = build_tree(payload, functions, root_id, args.max_depth, args.direction, args.include_source)
        summary = summarize_reachable(functions, globals_index, reachable, args.include_source)

        result = {
            "query": {
                "mode": "function",
                "root_function_id": root_id,
                "root_function_name": root_function["name"],
                "root_qualified_name": root_function["qualified_name"],
                "max_depth": args.max_depth,
                "direction": args.direction,
                "include_source": args.include_source,
            },
            "tree": tree,
            "summary": summary,
            "graph": {
                "adjacency": adjacency,
                "cycle_edges": sorted(edge for edge, is_cycle in cycle_edges.items() if is_cycle),
            },
        }

    if args.json:
        write_json_output(result, args.output)
        return 0

    write_json_output(build_compact_result(result, functions, args.include_source), args.output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
